force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Hotels</relationshipLabel>
    <relationshipName>Hotels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/PreReservation__c.object-meta.xml
<CustomObject>
    <label>PreReservation</label>
    <nameField>
        <label>PreReservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PreReservation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PreReservation__c/fields/ChekinDate__c.field-meta.xml
<CustomField>
    <fullName>ChekinDate__c</fullName>
    <label>ChekinDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/ChekoutDate__c.field-meta.xml
<CustomField>
    <fullName>ChekoutDate__c</fullName>
    <label>ChekoutDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipName>Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipName>Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>PreReservation</relationshipLabel>
    <relationshipName>PreReservation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/ArrivalDate__c.field-meta.xml
<CustomField>
    <fullName>ArrivalDate__c</fullName>
    <label>ArrivalDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/DepartureDate__c.field-meta.xml
<CustomField>
    <fullName>DepartureDate__c</fullName>
    <label>DepartureDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/NumberOfGuest__c.field-meta.xml
<CustomField>
    <fullName>NumberOfGuest__c</fullName>
    <label>NumberOfGuest</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Alcohol__c.field-meta.xml
<CustomField>
    <fullName>Alcohol__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Alcohol</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Internet__c.field-meta.xml
<CustomField>
    <fullName>Internet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Internet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/IsBooked__c.field-meta.xml
<CustomField>
    <fullName>IsBooked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsBooked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/IsBusy__c.field-meta.xml
<CustomField>
    <fullName>IsBusy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsBusy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Sauna__c.field-meta.xml
<CustomField>
    <fullName>Sauna__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sauna</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PrereservToReservPageController.cls
public class PrereservToReservPageController {
    public PreReservation__c prereserv{get; set;}
    public Reservation__c reserv{get; set;}
    public Room__c room{get;set;}
    Public String prereservid = System.currentPagereference().getParameters().get('prereservroom');
    
    public PrereservToReservPageController(){
        prereserv = new PreReservation__c();
        reserv = new Reservation__c();
        prereserv= [SELECT id,City__c, Hotel__c, Room__c,ChekinDate__c, ChekoutDate__c, Count__c, Email__c FROM PreReservation__c WHERE id=:prereservid];
        room=[SELECT id,IsBusy__c,IsBooked__c,
               Alcohol__c, Internet__c, Sauna__c FROM Room__c WHERE Room__c.id=:prereserv.Room__c];
        
    }
    
    public Pagereference save(){        
        try {
            reserv.City__c=prereserv.City__c;
            reserv.Hotel__c=prereserv.Hotel__c;
            reserv.Room__c=prereserv.Room__c;
            reserv.ArrivalDate__c=prereserv.ChekinDate__c;
            reserv.DepartureDate__c=prereserv.ChekoutDate__c;
            reserv.NumberOfGuest__c=prereserv.Count__c;
            reserv.ContactEmail__c=prereserv.Email__c;
            room.IsBooked__c = false;
            room.IsBusy__c=true;
            
            insert reserv;
            delete prereserv;
            update room;
            PageReference pref=new PageReference('/apex/ReservationPage');
            pref.setRedirect(true);
            return pref;
        }catch (DMLException e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, '"Something went wrong !"'));
            return null;
        }       
        
    }    
    public Pagereference cancel(){               

            PageReference pref=new PageReference('/apex/PrereservationPage');
            pref.setRedirect(true);
            return pref;
        
    }
}