force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Hotels</relationshipLabel>
    <relationshipName>Hotels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/PreReservation__c.object-meta.xml
<CustomObject>
    <label>PreReservation</label>
    <nameField>
        <label>PreReservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PreReservation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PreReservation__c/fields/ChekinDate__c.field-meta.xml
<CustomField>
    <fullName>ChekinDate__c</fullName>
    <label>ChekinDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/ChekoutDate__c.field-meta.xml
<CustomField>
    <fullName>ChekoutDate__c</fullName>
    <label>ChekoutDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipName>Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipName>Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>PreReservation</relationshipLabel>
    <relationshipName>PreReservation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Alcohol__c.field-meta.xml
<CustomField>
    <fullName>Alcohol__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Alcohol</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Internet__c.field-meta.xml
<CustomField>
    <fullName>Internet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Internet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/IsBooked__c.field-meta.xml
<CustomField>
    <fullName>IsBooked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsBooked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Sauna__c.field-meta.xml
<CustomField>
    <fullName>Sauna__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sauna</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EditPrereservPageController.cls
public class EditPrereservPageController {

    public PreReservation__c prereserv{get; set;}
    public Room__c editprereservroom{get;set;}
    Public String prereservid = System.currentPagereference().getParameters().get('prereservroom');
    
    public EditPrereservPageController(){
        prereserv = new PreReservation__c();
        prereserv= [SELECT id,City__c, Hotel__c, Room__c,ChekinDate__c, ChekoutDate__c, Count__c, Email__c FROM PreReservation__c WHERE id=:prereservid];
        editprereservroom= [SELECT id,City__c,Name, Hotel__c, IsBooked__c,
                        Alcohol__c, Internet__c, Sauna__c FROM Room__c WHERE id=:prereserv.Room__c];
    }
        
        
        public Pagereference save(){        
        try {                      
            update prereserv;
            update editprereservroom;
            PageReference pref=new PageReference('/apex/MainPage');
            pref.setRedirect(true);
            return pref;
        }catch (DMLException e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, '"Something went wrong !"'));
            return null;
        }       
        
    }    
    public Pagereference cancel(){               
            PageReference pref=new PageReference('/apex/MainPage');
            pref.setRedirect(true);
            return pref;
    }
        
}