force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Hotels</relationshipLabel>
    <relationshipName>Hotels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/PreReservation__c.object-meta.xml
<CustomObject>
    <label>PreReservation</label>
    <nameField>
        <label>PreReservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PreReservation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PreReservation__c/fields/ChekinDate__c.field-meta.xml
<CustomField>
    <fullName>ChekinDate__c</fullName>
    <label>ChekinDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/ChekoutDate__c.field-meta.xml
<CustomField>
    <fullName>ChekoutDate__c</fullName>
    <label>ChekoutDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipName>Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipName>Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>PreReservation</relationshipLabel>
    <relationshipName>PreReservation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/ArrivalDate__c.field-meta.xml
<CustomField>
    <fullName>ArrivalDate__c</fullName>
    <label>ArrivalDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/DepartureDate__c.field-meta.xml
<CustomField>
    <fullName>DepartureDate__c</fullName>
    <label>DepartureDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/NumberOfGuest__c.field-meta.xml
<CustomField>
    <fullName>NumberOfGuest__c</fullName>
    <label>NumberOfGuest</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Alcohol__c.field-meta.xml
<CustomField>
    <fullName>Alcohol__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Alcohol</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Internet__c.field-meta.xml
<CustomField>
    <fullName>Internet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Internet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/IsBooked__c.field-meta.xml
<CustomField>
    <fullName>IsBooked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsBooked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/IsBusy__c.field-meta.xml
<CustomField>
    <fullName>IsBusy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsBusy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Sauna__c.field-meta.xml
<CustomField>
    <fullName>Sauna__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sauna</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HotelReservTest.cls
@isTest
private class HotelReservTest {
    
    @testSetup
    static void createTestData() {
        City__c newCity=new City__c();
        newCity.name='Брест';
        insert newCity;
        Hotel__c newHotel=new Hotel__c();
        newHotel.name='Интурист';
        insert newHotel;
        Room__c newRoom=new Room__c();
        newRoom.name='301';
        insert newRoom;
    }
    
    @isTest static void test_AddReservPageController(){
        
        City__c newCity=new City__c();
        newCity.name='Брест';
        insert newCity;
        Hotel__c newHotel=new Hotel__c();
        newHotel.name='Интурист';
        insert newHotel;
        Room__c newRoom=new Room__c();
        newRoom.name='301';
        insert newRoom;
        
        
        try{
            PageReference pageRef = Page.AddReservPage;
            Test.setCurrentPage(pageRef);
            System.currentPagereference().getParameters().put('reservroom', newRoom.id);
            
            AddReservPageController ctrl1 = new AddReservPageController();
            ctrl1.save();
            ctrl1.cancel();
        } catch(DMLException e){
            system.assertEquals(e.getMessage(), e.getMessage());
            
        }
        
        
    }
    
    @isTest static void test_AddPreReservPageController(){
        City__c newCity=new City__c();
        newCity.name='Брест';
        insert newCity;
        Hotel__c newHotel=new Hotel__c();
        newHotel.name='Интурист';
        insert newHotel;
        Room__c newRoom=new Room__c();
        newRoom.name='301';
        insert newRoom;
        try{
            PageReference pageRef = Page.AddPreReservPage;
            Test.setCurrentPage(pageRef);
            System.currentPagereference().getParameters().put('prereservroom', newRoom.id);
            
            AddPreReservPageController ctrl2 = new AddPreReservPageController();
            ctrl2.save();
            ctrl2.cancel();
        } catch(DMLException e){
            system.assertEquals(e.getMessage(), e.getMessage());
            
        }
    }
    
    @isTest static void test_ReservationPageController(){
        City__c newCity=new City__c();
        newCity.name='Брест';
        insert newCity;
        Hotel__c newHotel=new Hotel__c();
        newHotel.name='Интурист';
        insert newHotel;
        Room__c newRoom=new Room__c();
        newRoom.name='301';
        insert newRoom;
        Reservation__c reserv=new Reservation__c();
        reserv.ContactEmail__c='ss@ss.ss';
        reserv.NumberOfGuest__c=5;
        Insert reserv;
        ReservationPageController ctrl3 = new ReservationPageController();
        system.assertEquals(reserv.ContactEmail__c, 'ss@ss.ss');
    }
    
    @isTest static void test_PreReservationPageController(){
        City__c newCity=new City__c();
        newCity.name='Брест';
        insert newCity;
        Hotel__c newHotel=new Hotel__c();
        newHotel.name='Интурист';
        insert newHotel;
        Room__c newRoom=new Room__c();
        newRoom.name='301';
        insert newRoom;
        PreReservation__c prereserv=new PreReservation__c();
        prereserv.Email__c ='ss@ss.ss';
        prereserv.Count__c=1;
        Insert prereserv;
        PreReservationPageController ctrl4 = new PreReservationPageController();
        system.assertEquals (prereserv.Count__c, 1);       
        
    }
    
    
    @isTest static void test_PreReservToReservPageController(){
        City__c newCity=new City__c();
        newCity.name='Брест';
        insert newCity;
        Hotel__c newHotel=new Hotel__c();
        newHotel.name='Интурист';
        insert newHotel;
        Room__c newRoom=new Room__c();
        newRoom.name='301';
        newRoom.IsBooked__c=true;
        insert newRoom;
        PreReservation__c prereserv=new PreReservation__c();
        Prereserv.Room__c=newRoom.Id;
        prereserv.Email__c ='ss@ss.ss';
        prereserv.Count__c=1;
        insert prereserv;
        
        try{
            PageReference pageRef = Page.PreReservToReservPage;
            Test.setCurrentPage(pageRef);
            System.currentPagereference().getParameters().put('prereservroom', prereserv.id);
            PreReservToReservPageController ctrl5 = new PreReservToReservPageController();
            ctrl5.room.id=newRoom.id;
            ctrl5.save();
            ctrl5.cancel();
        } catch(DMLException e){
            system.assertEquals(e.getMessage(), e.getMessage());
        }
    }
    
    @isTest static void test_EditReservPageController(){
        City__c newCity=new City__c();
        newCity.name='Брест';
        insert newCity;
        Hotel__c newHotel=new Hotel__c();
        newHotel.name='Интурист';
        insert newHotel;
        Room__c newRoom=new Room__c();
        newRoom.name='301';
        newRoom.Alcohol__c=false;
        newRoom.Sauna__c=false;
        newRoom.Internet__c=false;
        insert newRoom;
        Reservation__c reserv=new Reservation__c();
        reserv.Room__c=newRoom.Id;
        reserv.ContactEmail__c='ss@ss.ss';
        reserv.NumberOfGuest__c=5;
        Insert reserv;
        
        try{
            PageReference pageRef = Page.EditReservPage;
            Test.setCurrentPage(pageRef);
            System.currentPagereference().getParameters().put('reservroom', reserv.id);
            EditReservPageController ctrl6 = new EditReservPageController();
            ctrl6.reservroom.id=newRoom.id;
            ctrl6.reserv.NumberOfGuest__c = 2;        
            ctrl6.save();
            ctrl6.cancel();
        } catch(DMLException e){
            system.assertEquals(e.getMessage(), e.getMessage());
        }
    }
    
    @isTest static void test_EditPreReservPageController(){
        City__c newCity=new City__c();
        newCity.name='Брест';
        insert newCity;
        Hotel__c newHotel=new Hotel__c();
        newHotel.name='Интурист';
        insert newHotel;
        Room__c newRoom=new Room__c();
        newRoom.name='301';
        newRoom.Alcohol__c=false;
        newRoom.Sauna__c=false;
        newRoom.Internet__c=false;
        insert newRoom;
        PreReservation__c prereserv=new PreReservation__c();
        prereserv.Room__c=newRoom.Id;
        prereserv.Email__c='ss@ss.ss';
        prereserv.Count__c=5;
        Insert prereserv;
        
        try{
            PageReference pageRef = Page.EditPreReservPage;
            Test.setCurrentPage(pageRef);
            System.currentPagereference().getParameters().put('prereservroom', prereserv.Id);
            EditPrereservPageController ctrl7 = new EditPrereservPageController();
            ctrl7.editprereservroom.id=newRoom.id;
            ctrl7.prereserv.Count__c=1;
            ctrl7.save();
            ctrl7.cancel();
        } catch(DMLException e){
            system.assertEquals(e.getMessage(), e.getMessage());
        }
    }
    
    @isTest static void test_SitePreReservationPageController1(){
        
        City__c newCity=new City__c();
        newCity.name='Брест';
        insert newCity;
        Hotel__c newHotel=new Hotel__c();
        newHotel.name='Интурист';
        insert newHotel;
        Room__c newRoom=new Room__c();
        newRoom.name='301';
        newRoom.Amount__c=1;
        insert newRoom;
        PreReservation__c prereserv=new PreReservation__c();
        prereserv.Email__c='ss@ss.ss';
        prereserv.Count__c=5;
        Insert prereserv;       
        
        try{
            PageReference pageRef = Page.SiteReservationPage;
            Test.setCurrentPage(pageRef);
            SitePreReservationPageController ctrl8 = new SitePreReservationPageController();
            ctrl8.selectHotel();
            ctrl8.cnt=prereserv.Count__c;
            ctrl8.save();
            ctrl8.cancel();            
        } catch(DMLException e){
            system.assertEquals(e.getMessage(), e.getMessage());
        }
    }
    
    @isTest static void test_SitePreReservationPageController2(){
        
        City__c newCity=new City__c();
        newCity.name='Брест';
        insert newCity;
        Hotel__c newHotel=new Hotel__c();
        newHotel.name='Интурист';
        insert newHotel;
        Room__c newRoom=new Room__c();
        newRoom.name='301';
        newRoom.Amount__c=1;
        insert newRoom;
        PreReservation__c prereserv=new PreReservation__c();
        prereserv.Email__c='ss@ss.ss';
        prereserv.Count__c=1;
        Insert prereserv;       
        
        try{
            PageReference pageRef = Page.SiteReservationPage;
            Test.setCurrentPage(pageRef);
            SitePreReservationPageController ctrl8 = new SitePreReservationPageController();
            ctrl8.selectHotel();
            ctrl8.cnt=prereserv.Count__c;
            ctrl8.save();
            ctrl8.cancel();            
        } catch(DMLException e){
            system.assertEquals(e.getMessage(), e.getMessage());
        }        
        
    }
    
    @isTest static void test_MainPageListController1(){
        City__c newCity=new City__c();
        newCity.name='Брест';
        insert newCity;
        Hotel__c newHotel=new Hotel__c();
        newHotel.name='Интурист';
        insert newHotel;
        Room__c newRoom=new Room__c();
        newRoom.name='301';
        newRoom.IsBusy__c=true;
        insert newRoom;
        Reservation__c reserv=new Reservation__c();
        reserv.Room__c=newRoom.Id;
        reserv.ContactEmail__c='ss@ss.ss';
        reserv.NumberOfGuest__c=5;
        Insert reserv;
        
        try{
            PageReference pageRef = Page.MainPage;
            Test.setCurrentPage(pageRef);
            System.currentPagereference().getParameters().put('addpr', newRoom.id);
            MainPageListController ctrl9 = new MainPageListController();
            ctrl9.retrieveHotels();
            ctrl9.retrieveRooms();
            ctrl9.rid=newRoom.Id;            
            ctrl9.deleteReserv();
            
        } catch(DMLException e){
            system.assertEquals(e.getMessage(), e.getMessage());
        } 
    }
    @isTest static void test_MainPageListController2(){
        City__c newCity=new City__c();
        newCity.name='Брест';
        insert newCity;
        Hotel__c newHotel=new Hotel__c();
        newHotel.name='Интурист';
        insert newHotel;
        Room__c newRoom=new Room__c();
        newRoom.name='301';
        newRoom.IsBooked__c =true;
        insert newRoom;
        PreReservation__c prereserv=new PreReservation__c();
        Prereserv.Room__c=newRoom.Id;
        Prereserv.Email__c='ss@ss.ss';
        Prereserv.Count__c =5;
        Insert prereserv;
        
        try{
            PageReference pageRef = Page.MainPage;
            Test.setCurrentPage(pageRef);
            System.currentPagereference().getParameters().put('addpr', newRoom.id);
            MainPageListController ctrl9 = new MainPageListController();
            ctrl9.retrieveHotels();
            ctrl9.retrieveRooms();
            ctrl9.rid=newRoom.Id;            
            ctrl9.deleteReserv();
            
        } catch(DMLException e){
            system.assertEquals(e.getMessage(), e.getMessage());
        } 
        
    }
    @isTest static void test_CheckCountDateTriggerPrereserv(){
        City__c newCity=new City__c();
        newCity.name='Брест';
        insert newCity;
        Hotel__c newHotel=new Hotel__c();
        newHotel.name='Интурист';
        insert newHotel;
        Room__c newRoom=new Room__c();
        newRoom.name='301';
        insert newRoom;
        PreReservation__c prereserv=new PreReservation__c();
        prereserv.Email__c ='ss@ss.ss';
        prereserv.Count__c=-1;
        prereserv.ChekinDate__c=date.newinstance(2000, 1, 1);
        prereserv.ChekoutDate__c=date.newinstance(2000, 1, 1);
        try {
            Insert prereserv;  
        } catch(DMLException e){
            system.assertEquals(e.getMessage(), e.getMessage());
        } 
        
    }
    @isTest static void test_CheckNumberDateTriggerReserv(){
        City__c newCity=new City__c();
        newCity.name='Брест';
        insert newCity;
        Hotel__c newHotel=new Hotel__c();
        newHotel.name='Интурист';
        insert newHotel;
        Room__c newRoom=new Room__c();
        newRoom.name='301';
        insert newRoom;
        Reservation__c reserv=new Reservation__c();
        reserv.ContactEmail__c ='ss@ss.ss';
        reserv.NumberOfGuest__c =-1;        
        reserv.ArrivalDate__c =date.newinstance(2000, 1, 1);
        reserv.DepartureDate__c =date.newinstance(2000, 1, 1);
        try {
            Insert reserv;  
        } catch(DMLException e){
            system.assertEquals(e.getMessage(), e.getMessage());
        }
    }
    
    
}