force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Hotels</relationshipLabel>
    <relationshipName>Hotels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/PreReservation__c.object-meta.xml
<CustomObject>
    <label>PreReservation</label>
    <nameField>
        <label>PreReservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PreReservation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PreReservation__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipName>Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipName>Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>PreReservation</relationshipLabel>
    <relationshipName>PreReservation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Alcohol__c.field-meta.xml
<CustomField>
    <fullName>Alcohol__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Alcohol</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Internet__c.field-meta.xml
<CustomField>
    <fullName>Internet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Internet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/IsBooked__c.field-meta.xml
<CustomField>
    <fullName>IsBooked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsBooked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/IsBusy__c.field-meta.xml
<CustomField>
    <fullName>IsBusy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsBusy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/KindOfRoom__c.field-meta.xml
<CustomField>
    <fullName>KindOfRoom__c</fullName>
    <label>KindOfRoom</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>single room</fullName>
            </value>
            <value>
                <fullName>double room</fullName>
            </value>
            <value>
                <fullName>triple room</fullName>
            </value>
            <value>
                <fullName>quadruple room</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Room__c/fields/Sauna__c.field-meta.xml
<CustomField>
    <fullName>Sauna__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sauna</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MainPageListController.cls
public with sharing class MainPageListController {
    
    public List<City__c> Cities{get; set;}
    public List<Hotel__c> Hotels{get; set;}
    public List<Room__c> Rooms{get;set;}
    public String CityId{get; set;}
    public String hotelId{get;set;}
    public String rid{get; set ;}
    Public String addpr = System.currentPagereference().getParameters().get('addpr');
    
    public MainPageListController(){
        Cities = getCities();
    }

    private List<City__c> getCities(){
        List<City__c> listCities = [SELECT Id, Name FROM City__c];
        return listCities;
        
    }
    public void retrieveHotels(){
        Hotels = [SELECT Id, Name FROM Hotel__c WHERE City__c = :CityId];
    }
    
    public void retrieveRooms(){
        Rooms = [SELECT Id, Hotel__c,Name, KindOfRoom__c, Amount__c,IsBooked__c,IsBusy__c,
                 Alcohol__c, Internet__c, Sauna__c FROM Room__c WHERE hotel__c = :hotelId];
    }
    
    public void deleteReserv(){
        Room__c delBusy=[select id,IsBusy__c,IsBooked__c,
                         Alcohol__c, Internet__c, Sauna__c from Room__c where id=:rid];
        
        if (delBusy.IsBusy__c==true){
            Reservation__c delres=[select id from Reservation__c where Room__c=:delBusy.Id ];
            delBusy.IsBusy__c=false;
            delBusy.Alcohol__c=false;
            delBusy.Internet__c=false;
            delBusy.Sauna__c=false;
            delete delres;
            update delBusy;
            Rooms = [SELECT Id, Hotel__c,Name, KindOfRoom__c, Amount__c,IsBooked__c,IsBusy__c,
                 Alcohol__c, Internet__c, Sauna__c FROM Room__c WHERE hotel__c = :hotelId];
        }
        if (delbusy.IsBooked__c==true){
            PreReservation__c delpreres=[select id from PreReservation__c where Room__c=:delBusy.Id ];
            delBusy.IsBooked__c=false;
            delBusy.Alcohol__c=false;
            delBusy.Internet__c=false;
            delBusy.Sauna__c=false;
            delete delpreres;
            update delBusy;
            Rooms = [SELECT Id, Hotel__c,Name, KindOfRoom__c, Amount__c,IsBooked__c,IsBusy__c,
                 Alcohol__c, Internet__c, Sauna__c FROM Room__c WHERE hotel__c = :hotelId]; 
            
        }
        
    }
    
    
}