force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Hotels</relationshipLabel>
    <relationshipName>Hotels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/ArrivalDate__c.field-meta.xml
<CustomField>
    <fullName>ArrivalDate__c</fullName>
    <label>ArrivalDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/DepartureDate__c.field-meta.xml
<CustomField>
    <fullName>DepartureDate__c</fullName>
    <label>DepartureDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/NumberOfGuest__c.field-meta.xml
<CustomField>
    <fullName>NumberOfGuest__c</fullName>
    <label>NumberOfGuest</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Alcohol__c.field-meta.xml
<CustomField>
    <fullName>Alcohol__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Alcohol</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Internet__c.field-meta.xml
<CustomField>
    <fullName>Internet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Internet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/IsBooked__c.field-meta.xml
<CustomField>
    <fullName>IsBooked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsBooked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Sauna__c.field-meta.xml
<CustomField>
    <fullName>Sauna__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sauna</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EditReservPageController.cls
public class EditReservPageController {
    public Reservation__c reserv{get; set;}
    public Room__c reservroom{get;set;}
    Public String reservid = System.currentPagereference().getParameters().get('reservroom');
    
    public EditReservPageController(){
        reserv = new Reservation__c();
        reserv= [SELECT id,City__c, Hotel__c, Room__c,ArrivalDate__c, DepartureDate__c, NumberOfGuest__c, ContactEmail__c FROM Reservation__c WHERE id=:reservid];
        reservroom= [SELECT id,City__c,Name, Hotel__c, IsBooked__c,
                     Alcohol__c, Internet__c, Sauna__c FROM Room__c WHERE id=:reserv.Room__c];
    }
    
    
    public Pagereference save(){        
        try {                      
            update reserv;
            update reservroom;
            PageReference pref=new PageReference('/apex/ReservationPage');
            pref.setRedirect(true);
            return pref;
        }catch (DMLException e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, '"Something went wrong !"'));
            return null;
        }       
        
    }    
    public Pagereference cancel(){               
        PageReference pref=new PageReference('/apex/ReservationPage');
        pref.setRedirect(true);
        return pref;
    }
    
}